### ISSUE TITLE
FATAL UNHANDLED EXCEPTION: System.NullReferenceException

### ISSUE THREAD

**Issue by stimpzon** [lformella/xdcc-grabscher#76] opened 2014-11-09 08:55 UTC
Hi,

i tried to install XG 3.3.0.0. Just unpacked the archive and started XG with "mono XG.Application.exe". XG immediately exits with the following message:

```
FATAL [ 1] 0:XG.Plugin.AWorker.Start()
System.EntryPointNotFoundException: FlushFileBuffers
  at (wrapper managed-to-native) Sharpen.IO.RandomAccessFile:FlushFileBuffers (Microsoft.Win32.SafeHandles.SafeFileHandle)
  at Sharpen.IO.RandomAccessFile.Sync () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.IO.FileStorage+FileBin.Sync () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.IO.BinDecorator.Sync () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.IO.CachingBin.Sync () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.IO.BinDecorator.Sync () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.IO.BlockAwareBin.Sync () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.SyncAndClose (IBin bin) [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.CloseDatabaseFile () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.ShutdownDataStorage () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Internal.ObjectContainerBase.ShutdownObjectContainer () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Internal.ObjectContainerBase+_IRunnable_129.Run () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Foundation.DynamicVariable.With (System.Object value, IRunnable block) [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Foundation.Environments.RunWith (IEnvironment environment, IRunnable runnable) [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Internal.ObjectContainerBase.WithEnvironment (IRunnable runnable) [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Internal.ObjectContainerBase.Open () [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Internal.IoAdaptedObjectContainer..ctor (IConfiguration config, System.String fileName) [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Internal.ObjectContainerFactory.OpenObjectContainer (IEmbeddedConfiguration config, System.String databaseFileName) [0x00000] in <filename unknown>:0
  at Db4objects.Db4o.Db4oEmbedded.OpenFile (IEmbeddedConfiguration config, System.String databaseFileName) [0x00000] in <filename unknown>:0
  at XG.DB.Dao.StartRun () [0x00000] in <filename unknown>:0
  at XG.Plugin.AWorker.Start (System.String aName, Boolean aNewThread) [0x00000] in <filename unknown>:0

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at XG.Business.Helper.Objects.CheckAndRemoveDuplicates (XG.Model.Domain.Servers aServers) [0x00000] in <filename unknown>:0
  at XG.Business.App..ctor () [0x00000] in <filename unknown>:0
  at XG.Application.Programm.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at XG.Business.Helper.Objects.CheckAndRemoveDuplicates (XG.Model.Domain.Servers aServers) [0x00000] in <filename unknown>:0
  at XG.Business.App..ctor () [0x00000] in <filename unknown>:0
  at XG.Application.Programm.Main (System.String[] args) [0x00000] in <filename unknown>:0
```

Some system details, let me know if you need more:

```
Ubuntu 12.04.5 LTS

Mono JIT compiler version 3.2.2 (mono-3-2/6a0d1e6 So 29. Dez 15:38:13 CET 2013)
Copyright (C) 2002-2012 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by lformella** [comment] 2014-11-09 09:12
Duplicate of #72 - please look there for a quick solution.

**Comment by stimpzon** [comment] 2014-11-09 09:13
Yes, found it just seconds ago... sorry for double posting ;)

**Closed as completed by lformella** 2014-11-09 09:12 UTC
Labels: duplicate
